# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dc983db6ebc9bdb99ba6f34bfb1238f751331dca35a12da720ddadc1c3cf100dca9f85b58b3988e951c808e95cea0df28b0c84e3affcab0486ae828302727eb

test:
  secret_key_base: 308f44a53ab36337361c1aa5163befe8d01a544c66c72c18ed1ac4badf859a3eddd071945a378584fdaf3ea0382520ee6f5604e4bb02e1a6862d20ea641de694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
